version: 0.0
os: linux
files:
  - source: webapp
    destination: /srv/weatherapp/webapp
  - source: scripts
    destination: /srv/weatherapp/scripts
permissions:
  - object: /srv/weatherapp
    owner: ec2-user
    group: ec2-user
    mode: 755
    type: [directory, file]
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_service.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      runas: root